services:
  psychodns:
    image: coredns/coredns:1.12.0
    container_name: psychodns
    restart: always
    volumes:
      - ./:/etc/psychodns
    networks:
      psychosis:
        ipv4_address: 192.168.200.2
    command:
      - "-conf"
      - "/etc/psychodns/Corefile"

networks:
  psychostorage:
  psychosis:
    name: psychosis
    ipam:
      config:
        - subnet: 192.168.200.0/24
