services:
  psychodns:
    image: marcorentap/hallucinet
    container_name: psychodns
    environment:
      - NETWORK=psychosis
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      psychosis:
        ipv4_address: 192.168.100.2
      
networks:
  psychosis:
    name: psychosis
    ipam:
      config:
        - subnet: 192.168.100.0/24
